{
  "errorCode" : "UNKNOWN_ERROR",
  "messages" : [ "500 INTERNAL_SERVER_ERROR \"Server error\"" ],
  "dataErrors" : [ ],
  "attributes" : {
    "traceId" : "40e1488ed0001adc",
    "exception" : "ResponseStatusException",
    "startTime" : "2020-11-27T11:17:40.095818Z"
  }
}