{
  "errorCode" : "UNKNOWN_ERROR",
  "messages" : [ "Another message" ],
  "dataErrors" : [ ],
  "attributes" : {
    "traceId" : "40e1488ed0001adc",
    "exception" : "RuntimeException",
    "startTime" : "2020-11-27T11:17:40.095818Z"
  }
}